### ISSUE TITLE
关于数据集的一些问题

### ISSUE THREAD

**Issue by cruise-tgu** [beifengchuizoudemeng/CWRU#3]
官网上下载的数据都是以数字命名的，并没有您所提供的那些后缀，是您自己修改的吗？

**Comment by beifengchuizoudemeng** [comment]
数据命名是为了方便统一处理数据，格式为转速+引入故障尺寸+引入故障位置

**Comment by cruise-tgu** [comment]
> 数据命名是为了方便统一处理数据，格式为转速+引入故障尺寸+引入故障位置
你好可以留个联系方式吗
我还有一些问题需要向您咨询可以吗

**Comment by beifengchuizoudemeng** [comment]
qq号：1542072481，备注学校及研究方向
